#+TITLE: Running Keyword Service
#+AUTHOR: VLEAD
#+DATE: [2017-05-02 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document captures a high level design of the application.


* Creation of Virtual Environment
  + Create Virtual Environment in the =nptl-data-service= directory
  #+BEGIN_EXAMPLE
  virtualenv venv
  #+END_EXAMPLE
  + Activate the Virtual Environment
  #+BEGIN_EXAMPLE
  source venv/bin/activate
  #+END_EXAMPLE


* Set up dependencies
  1. Install all the required dependencies
  #+BEGIN_EXAMPLE
  pip install flask
  pip install flask-cors
  pip install flask-testing
  pip install requests
  pip install pyyaml
  #+END_EXAMPLE
* Clone the service repository 
   1. Clone the repository to your machine.
      #+BEGIN_EXAMPLE
      git clone <<copied url>>
      #+END_EXAMPLE
   2. Change directory to the cloned folder.
      #+BEGIN_EXAMPLE
      cd <<cloned directory in the local machine>>
      #+END_EXAMPLE
   3. Run make
      #+BEGIN_EXAMPLE
      make
      #+END_EXAMPLE
   4. If successfully done, a build folder will be created in the cloned
      directory.


* Insert Default data 
   1. go to the code folder and change the PYTHONPATH
      #+BEGIN_EXAMPLE
      cd </yourDestinationDirectory/build/code>
      export PYTHONPATH=$(pwd)
      #+END_EXAMPLE


* Run the application
   1. Navigate to rest folder
      #+BEGIN_EXAMPLE
      cd <</code/runtime/rest>>
      #+END_EXAMPLE
   2. Unset the proxy
      #+BEGIN_EXAMPLE
      unset http_proxy
      unset https_proxy
      #+END_EXAMPLE
   3. Run the app.
      #+BEGIN_EXAMPLE
      python app.py
      #+END_EXAMPLE
   3. If everything is fine, the service will start.


* Access the application 
   1. Initially, Keywords present for testing are : test, hello, data, cmos,
      Numerical, Approximation, Numerical Approximation.
   2. Any of the keyword can be used to test the service running.
   3. To check the result of the service, open url : 
      #+BEGIN_EXAMPLE
      http://localhost:5000/search?key=yourChosenKeyword
      #+END_EXAMPLE
   4. A few examples are explained below, Kindly go through them.


* Sample Examples of running the service
*** API Designs 
**** Get all url for a keyword
  :PROPERTIES:
  :CUSTOM_ID: api_get_all_labs
  :END:    
  - URL :: /search?key=keyword

  - Method :: GET

  - URL Params ::  None

  - Payload :: 

  - Example:
#+BEGIN_EXAMPLE
http://localhost:5000/search?key=test
#+END_EXAMPLE
#+BEGIN_EXAMPLE
[
results:"{
"test": [
        "http://nptel.ac.in/courses/117101105/1",
        "http://nptel.ac.in/courses/117101105/2",
        "http://nptel.ac.in/courses/117101105/3"
        ], 
        [
        "https://nptel.ac.in/courses/117101105/4",
        "https://nptel.ac.in/courses/117101105/5",
        "https://nptel.ac.in/courses/117101105/6"
        ]
        }" 
]
#+END_EXAMPLE	       

  - Example:
#+BEGIN_EXAMPLE
http://localhost:5000/search?key=cmos
#+END_EXAMPLE
#+BEGIN_EXAMPLE
[
results:"{
"cmos": [
        "http://nptel.ac.in/courses/117101105/1",
        "http://nptel.ac.in/courses/117101105/2",
        "http://nptel.ac.in/courses/117101105/3"
        ]
        }" 
]
#+END_EXAMPLE


  - Example:
#+BEGIN_EXAMPLE
http://localhost:5000/search?key=hello
#+END_EXAMPLE
#+BEGIN_EXAMPLE
[
results:"{
"hello": [
        "http://nptel.ac.in/courses/117101105/7",
        "http://nptel.ac.in/courses/117101105/8",
        "http://nptel.ac.in/courses/117101105/9"
        ], 
        }" 
]
#+END_EXAMPLE

